#ifndef __CONSTANTS__
#define __CONSTANTS__

static int NUMBER_OF_DIFFERENT_MEDICINES_PER_PRODUCTION_LINE=0;
static int NUMBER_OF_PRODUCTION_LINES=0;
static int MAX_ALLAWOD_NUMBER_OF_BOTTLED_OUTOF_SPEC=0;
static int MAX_ALLAWOD_NUMBER_OF_BILL_OUTOF_SPEC=0;
static int SIMULATION_MAX_TIME=0;
static int NUMBER_OF_INSPECTION_AND_PACKAGING_EMPLOYEES=0;
static int MAXIMUM_NUMBER_OF_PLASTIC_CONTAINERS=0;
static int MAXIMUM_NUMBER_ALLOWED_FOR_TYPE=0;
static int LIQUID_LEVEL_ACCEPTED_RANGE_MIN=0;
static int LIQUID_LEVEL_ACCEPTED_RANGE_MAX=0;
static int LIQUID_LEVEL_GENERATED_MIN=0;
static int LIQUID_LEVEL_GENERATED_MAX=0;
static int TIME_NEEDED_FOR_EMPLOYEE_MIN=0;
static int TIME_NEEDED_FOR_EMPLOYEE_MAX=0;
static int NUM_OF_INSPECTION_EMPLOYEES=0;
static int NUM_OF_PACKAGING_EMPLOYEES=0;

#endif


